### ISSUE TITLE
npm transfer

### ISSUE THREAD

**Issue by dutu** [iainreid820/kraken-api-client#1]
Hi @iainjreid, if you are not planning to work on this module anymore, would you be eager to let me take ownership of this module name on npm?

Thanks you!

**Comment by iainjreid** [comment]
Apologies for the delay. No problem at all! Could you post which username I should transfer ownership over to @dutu?

**Comment by dutu** [comment]
Thank you!
yes my npm username is `dutu` and from what I know it would suffice to add me as an owner for the npm package
```shell
npm owner add dutu kraken-api-client
```

**Comment by iainjreid** [comment]
Invitation sent over, do remove me when you have accepted, good luck with your package 🙌

**Comment by dutu** [comment]
Excellent, thanks a lot!
Please send me a Bitcoin or Monero address, so I can buy you a beer :)

**Comment by iainjreid** [comment]
Haha, no need, you're doing me a favour too, one less dead package on my account!
